# 1. Introduction, Problem Statement & Objective

Tema: SDGs 3 - Good Health and Well Being

Model: Logistic Regression (From Scratch)

# 2. Dataset Details:
Cervical Cancer Behavior Risk (UCI) = https://archive.ics.uci.edu/dataset/537/cervical+cancer+behavior+risk

# 3. Data Preprocessing & Exploratory Data Analysis

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [7]:
file_path = 'dataset/sobar-72.csv'
df = pd.read_csv(file_path)
display(df.head())

print("\n--- Informasi Dataset ---")
df.info()

,behavior_sexualRisk,behavior_eating,behavior_personalHygine,intention_aggregation,intention_commitment,attitude_consistency,attitude_spontaneity,norm_significantPerson,norm_fulfillment,perception_vulnerability,perception_severity,motivation_strength,motivation_willingness,socialSupport_emotionality,socialSupport_appreciation,socialSupport_instrumental,empowerment_knowledge,empowerment_abilities,empowerment_desires,ca_cervix
0,10,13,12,4,7,9,10,1,8,7,3,14,8,5,7,12,12,11,8,1
1,10,11,11,10,14,7,7,5,5,4,2,15,13,7,6,5,5,4,4,1
2,10,15,3,2,14,8,10,1,4,7,2,7,3,3,6,11,3,3,15,1
3,10,11,10,10,15,7,7,1,5,4,2,15,13,7,4,4,4,4,4,1
4,8,11,7,8,10,7,8,1,5,3,2,15,5,3,6,12,5,4,7,1

--- Informasi Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   behavior_sexualRisk         72 non-null     int64
 1   behavior_eating             72 non-null     int64
 2   behavior_personalHygine     72 non-null     int64
 3   intention_aggregation       72 non-null     int64
 4   intention_commitment        72 non-null     int64
 5   attitude_consistency        72 non-null     int64
 6   attitude_spontaneity        72 non-null     int64
 7   norm_significantPerson      72 non-null     int64
 8   norm_fulfillment            72 non-null     int64
 9   perception_vulnerability    72 non-null     int64
 10  perception_severity         72 non-null     int64
 11  motivation_strength         72 non-null     int64
 12  motivation_willingness      72 non-null     int64
 13  socialSupport_emotionality  72 non-null     int64
 14  socialSupport_appreciation  72 non-null     int64
 15  socialSupport_instrumental  72 non-null     int64
 16  empowerment_knowledge       72 non-null     int64
 17  empowerment_abilities       72 non-null     int64
 18  empowerment_desires         72 non-null     int64
 19  ca_cervix                   72 non-null     int64
dtypes: int64(20)
memory usage: 11.4 KB

In [8]:
#Error handling

#datatype handling
print(df.dtypes)
df.replace('?', np.nan, inplace=True)
df = df.astype(float)

#missing value handling
print(df.isnull().sum())
df.fillna(df.median(), inplace=True)

#normalization handling
X = df.drop(columns=['ca_cervix'])
y = df['ca_cervix']

X_normalized = (X - X.min()) / (X.max() - X.min())

display(X_normalized.head())

behavior_sexualRisk           int64
behavior_eating               int64
behavior_personalHygine       int64
intention_aggregation         int64
intention_commitment          int64
attitude_consistency          int64
attitude_spontaneity          int64
norm_significantPerson        int64
norm_fulfillment              int64
perception_vulnerability      int64
perception_severity           int64
motivation_strength           int64
motivation_willingness        int64
socialSupport_emotionality    int64
socialSupport_appreciation    int64
socialSupport_instrumental    int64
empowerment_knowledge         int64
empowerment_abilities         int64
empowerment_desires           int64
ca_cervix                     int64
dtype: object
behavior_sexualRisk           0
behavior_eating               0
behavior_personalHygine       0
intention_aggregation         0
intention_commitment          0
attitude_consistency          0
attitude_spontaneity          0
norm_significantPerson        0
norm_fulfillment              0
perception_vulnerability      0
perception_severity           0
motivation_strength           0
motivation_willingness        0
socialSupport_emotionality    0
socialSupport_appreciation    0
socialSupport_instrumental    0
empowerment_knowledge         0
empowerment_abilities         0
empowerment_desires           0
ca_cervix                     0
dtype: int64

,behavior_sexualRisk,behavior_eating,behavior_personalHygine,intention_aggregation,intention_commitment,attitude_consistency,attitude_spontaneity,norm_significantPerson,norm_fulfillment,perception_vulnerability,perception_severity,motivation_strength,motivation_willingness,socialSupport_emotionality,socialSupport_appreciation,socialSupport_instrumental,empowerment_knowledge,empowerment_abilities,empowerment_desires
0,1.00,0.833333,0.750000,0.25,0.111111,0.875,1.000000,0.0,0.416667,0.333333,0.125,0.916667,0.416667,0.166667,0.625,0.750000,0.750000,0.666667,0.416667
1,1.00,0.666667,0.666667,1.00,0.888889,0.625,0.500000,1.0,0.166667,0.083333,0.000,1.000000,0.833333,0.333333,0.500,0.166667,0.166667,0.083333,0.083333
2,1.00,1.000000,0.000000,0.00,0.888889,0.750,1.000000,0.0,0.083333,0.333333,0.000,0.333333,0.000000,0.000000,0.500,0.666667,0.000000,0.000000,1.000000
3,1.00,0.666667,0.583333,1.00,1.000000,0.625,0.500000,0.0,0.166667,0.083333,0.000,1.000000,0.833333,0.333333,0.250,0.083333,0.083333,0.083333,0.083333
4,0.75,0.666667,0.333333,0.75,0.444444,0.625,0.666667,0.0,0.166667,0.000000,0.000,1.000000,0.166667,0.000000,0.500,0.750000,0.166667,0.083333,0.333333

In [9]:
# Data Splitting (Training 80% & Testing 20%)
X_array = X_normalized.values
y_array = y.values

np.random.seed(42)
shuffled_indices = np.random.permutation(len(X_array))
X_shuffled = X_array[shuffled_indices]
y_shuffled = y_array[shuffled_indices]

split_idx = int(0.8 * len(X_array))

X_train, X_test = X_shuffled[:split_idx], X_shuffled[split_idx:]
y_train, y_test = y_shuffled[:split_idx], y_shuffled[split_idx:]

print(f"Total Train Data: {len(X_train)}")
print(f"Total Test Data: {len(X_test)}")

Total Train Data: 57
Total Test Data: 15

# 4. Logistic Regression Implementation

In [11]:
class CustomLogisticRegression:
    def __init__(self, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None
        self.loss_history = []

    def sigmoid(self, z):
        z = np.clip(z, -250, 250)
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        
        
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        
        for i in range(self.epochs):
            # z = (X * W) + b
            linear_model = np.dot(X, self.weights) + self.bias
            
    
            y_predicted = self.sigmoid(linear_model)

            #kepelesetan data
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            # updating weights
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

            # saving error value (Binary Cross-Entropy Loss) each 100 itteration
            if i % 100 == 0:
                epsilon = 1e-9 # Mencegah error log(0)
                loss = - (1 / n_samples) * np.sum(y * np.log(y_predicted + epsilon) + (1 - y) * np.log(1 - y_predicted + epsilon))
                self.loss_history.append(loss)

    def predict_probabilities(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X, threshold=0.5):
        y_predicted = self.predict_probabilities(X)
        return np.array([1 if i > threshold else 0 for i in y_predicted])

In [12]:
# Training Model
model = CustomLogisticRegression(learning_rate=0.1, epochs=2000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Training Process Finished ")
print("Model Guess Result on Testing Data:", y_pred)
print("Original Answer from Testing Data  :", y_test)

Training Process Finished
Model Guess Result on Testing Data: [0 0 0 0 0 0 1 0 0 1 0 1 0 1 0]
Original Answer from Testing Data  : [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.]

# 5. Result Validation & Metrics